name: reward
replicaCount: 1

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/reward
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30030
  targetport: 30030

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
namespace: 'dev'

##for liveness and readiness
path: '/health'
port: 30030
