name: email
replicaCount: 1

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/email
  pullPolicy: Always
  email: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30042
  targetport: 30042

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercenemaile:
namespace: 'test'

##for liveness and readiness
path: '/health'
port: 30042
