name: calendar-frontend
replicaCount: 1

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/calendar-frontend
  pullPolicy: Always
  tag: ""

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 3000
  targetport: 3000

# resources: 
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage:   
namespace: "calendar-dev"
  
##for liveness and readiness
path: "/"
port: 3000


