apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.name }}
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
    PORT: "30020"
    HOST: "0.0.0.0"
    
    DB_HOST: {{ .Values.DB_HOST }}
    DB_USER: {{ .Values.DB_USER }}
    DB_PASS: {{ .Values.DB_PASS }}
    DB: "viwell-activity"
