apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/secure-backends: "false"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Frame-Options: Deny";
        more_set_headers "X-Xss-Protection: 1; mode=block";
        more_set_headers "X-Content-Type-Options: nosniff";
        more_clear_headers "Cache-Control";
        more_set_headers "server: hide";
        more_set_headers "Cache-Control must-revalidate";  
        more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload";
        more_set_headers "Content-Security-Policy: default-src 'self';" always;
    nginx.org/client-max-body-size: "0"
  name: {{ .Values.name }}
spec:
  rules:
  - host: stagging-api.viwell.com
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.name }}
            port:
              number: {{ .Values.port }}
        path: /
        pathType: ImplementationSpecific
