name: personalisation
replicaCount: 1

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/personalisation
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 30027
  targetport: 30027

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage:
namespace: 'prod'

##for liveness and readiness
path: '/health'
port: 30027
