name: pillar
replicaCount: 1

image:
  repository: 814880204573.dkr.ecr.us-east-1.amazonaws.com/pillar
  pullPolicy: Always
  tag: ''

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 3009
  targetport: 3009

# resources:
#   requests:
#     cpu: 250m
#     memory: 128m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage:
namespace: 'test'

##for liveness and readiness
path: '/health'
port: 3009
