apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  labels:
    env: {{ .Values.name }}
  annotations:
    # "helm.sh/hook": pre-upgrade
    # "helm.sh/hook-delete-policy": before-hook-creation
    # "helm.sh/hook-weight": "0"    
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        envFrom:
          - configMapRef:
             name: {{ .Values.name }}        
#           - configMapRef:
#              name: {{ .Values.name }}